a = 1/4;
b = 1/16;
m = 8;
n = 8;
s = 20;
t = linspace(-5,5,intmax('int8'));
k = 1:1:intmax('int8');
k = double(k);
x = cos(t) - a*cos(t.*m) + b*sin(t.*n);
x = double(x);
y = sin(t) + a*sin(t.*m) + b*cos(t.*n);
y = double(y);
plot(x./k,y./k);